### ISSUE TITLE
Missing source file jcm.dll

### ISSUE THREAD

**Issue by Ashish-Kotwal** [CCSI-Toolset/MEA_dm#6]
The file '.opt' directs the file jcm.dll, which I believe it is a dynamic link library. Does ASPEN now present the required file with its original installation?

**Comment by ksbeattie** [comment]
Hi @Ashish-Kotwal, the 'jcm.dll' file is required and is downloadable from the [release page](https://github.com/CCSI-Toolset/MEA_dm/releases), just below where you downloaded the model itself, in the Assets section.  It should be possible to build that dll file yourself, but I believe we'd need to update the docs to include those instructions.

**Comment by Ashish-Kotwal** [comment]
Hello @ksbeattie sir, 
Thank you for update, I was planning to update this issue with solution which I forgot to upload it. 
Essentially, after little bit of Google search I realized that the 'jcm.dll' is computer generated dynamic link library (.dll file), which is available on individual user's computer after Fortran compiler reads and converts the user developed Fortran code to machine readable byte code.
The instructions for ''how to do it'' need to be added in pdf file (tutorial file).

**Comment by ksbeattie** [comment]
@Ashish-Kotwal, thank you for pointing that out.

Would you be willing to provide those instructions that need to be added to the pdf file?  If so, I'll make sure it get added.
